language: php
sudo: false

php:
  - 7.2

addons:
  mariadb: '10.2'

before_script:
  - mysql -e 'CREATE DATABASE test;'
  - composer self-update
  - composer install --dev --prefer-dist --no-interaction

script:
  - php vendor/bin/doctrine orm:schema-tool:drop -n --force
  - php vendor/bin/doctrine orm:schema-tool:create -n
  - php vendor/bin/doctrine orm:schema-tool:update --dump-sql
  - php vendor/bin/doctrine orm:validate-schema -n
  - rm src/Entity/Admin.php
  - mv AdminEdited.php src/Entity/Admin.php
  - php vendor/bin/doctrine-migrations migrations:diff --configuration=config/migrations.yml -n
  - php vendor/bin/doctrine-migrations migrations:migrate --configuration=config/migrations.yml -n
  - php vendor/bin/doctrine orm:validate-schema -n

cache:
  directories:
    - $COMPOSER_CACHE_DIR
